# Generated by Django 3.2 on 2022-02-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contactus_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='receiver',
        ),
    ]
