# Generated by Django 3.2 on 2022-02-24 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productreview_review_rating'),
        ('wishlists', '0002_auto_20220222_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liked_item', to='products.product'),
        ),
    ]
