# Generated by Django 3.2 on 2022-02-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0004_alter_wishlistitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='name',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
