# Generated by Django 3.2 on 2022-02-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220201_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_product',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
