# Generated by Django 3.2 on 2022-02-04 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220203_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_product',
        ),
    ]
