# Generated by Django 3.2 on 2022-02-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productreview_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
