# Generated by Django 3.2 on 2022-02-25 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_quantity_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='selectable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'selectable': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
    ]
